# @package dataset
defaults:
  - /dataset/default
_target_: lightning_transformers.core.nlp.HFDataModule
cfg:
  dataset_name: null  # 这个是从 hugging face 数据集倒过来
  dataset_config_name: null  # hugging face 数据集的配置
  train_file: null  # 本地自建
  validation_file: null  # 本地自建
  test_file: null  # 本地自建
  train_val_split: null  # 指定 hf 的 train_test_split test_size=0.25 train_size=0.75
  max_samples: null
  cache_dir: null  # 指定 hugging face 数据集的缓存地址
  padding: 'max_length'
  truncation: 'only_first'
  preprocessing_num_workers: 1
  load_from_cache_file: True
  max_length: 128
  limit_train_samples: null  # 限制数据条数
  limit_val_samples: null  # 限制数据条数
  limit_test_samples: null  # 限制数据条数
